version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/users-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(users)"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "npm"
    directory: "/academic-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(academic)"
    labels:
      - "dependencies"
      - "security"

  - package-ecosystem: "npm"
    directory: "/api-gateway"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(api)"
    labels:
      - "dependencies"
      - "security"